version: "3"
services:
  mysql-service:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=tasktest
      - MYSQL_USER=root
      - MYSQL_PASSWORD=13112000Nhatrang
      - MYSQL_ROOT_PASSWORD=13112000Nhatrang
  spring-service:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mysql-service
